### PR TITLE
Swift 2.0 compatibility

### PR DESCRIPTION
**Pull request by jgarth**
Hi, 

I updated your code to work with Xcode 7 beta 5. Test are passing. Feel free to pull these changes if you want them :) Other projects seem to use a `swift-2.0` branch to facilitate people using their Pods with the Xcode beta and not get mixed up with the latest stable version.

Cheers.

### CODE REVIEW

**Comment by icodesign** [comment]
Thanks! :+1:

**Comment by icodesign** [comment]
@jgarth Sorry for my mistake. I've added a new branch `swift-2.0`, so would you create a new pull request to the branch?

**Comment by jgarth** [comment]
Hey @iCodesign,

I can't create a new PR because my commits are already in the `swift-2.0` branch :) You can just `git revert` your commit 45e85cc3378b046f085bb29c8fe44b31196fb5f3 (the one that reverted the changes in the first place) and so the changes will be in the branch again. :+1:

**Comment by icodesign** [comment]
@jgarth Done!

**Pull request merged**
