### PR TITLE
Updated to support Swift 2.3

### PR DESCRIPTION
**Pull request by nmccann**

### CODE REVIEW

**Comment by nmccann** [comment]
Alternatively we could return an optional image instead of assuming the image will be non-nil, and then the user of the library could handle the nil case (or force unwrap it).

**Comment by icodesign** [comment]
Well, I'm in favor of returning a an optional image. Force unwrap is not safe. What do you think?

**Comment by icodesign** [comment]
And I also believe that you should change the project settings along with the `UIImage` API changes, you should get a alert of migrating to Swift 2.3 after opening the project in Xcode 8 Beta. Could you do that?

**Comment by nmccann** [comment]
Sure, I'll make those changes.

**Pull request merged**
